Make the Python package follow typical directory structure (https://docs.python.org/3/tutorial/modules.html#packages).
Without this, following the instructions doesn't work:

	Traceback (most recent call last):
	  File "coding/main_initialisation.py", line 29, in <module>
	    from coding.constants import Constants
	ModuleNotFoundError: No module named 'coding'

This is because relative to coding/main_initialisation.py, there is no
'coding' module.

There's more reorganization that could be useful, but this just gets
things running.